//! # Bootsandcats OAuth2 Client
//!
//! A Rust client for the OAuth2 Authorization Server API with OpenTelemetry support.
//!
//! ## Example
//!
//! ```rust,no_run
//! use bootsandcats_oauth2_client::{Configuration, Error};
//!
//! #[tokio::main]
//! async fn main() -> Result<(), Error> {
//!     let config = Configuration::new("https://auth.example.com")
//!         .with_bearer_token("your-access-token");
//!     
//!     // Use the generated API clients here
//!     Ok(())
//! }
//! ```

pub mod configuration;
pub mod error;

#[cfg(feature = "tracing")]
pub mod tracing;

// Re-exports
pub use configuration::Configuration;
pub use error::Error;

// Note: The following modules will be generated by OpenAPI Generator
// pub mod apis;
// pub mod models;
