-- Create security_audit_events table for H2 compatibility
CREATE TABLE IF NOT EXISTS security_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL UNIQUE,
    event_type VARCHAR(100) NOT NULL,
    event_category VARCHAR(50) NOT NULL,
    event_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    -- Actor information
    principal VARCHAR(255),
    principal_type VARCHAR(50),
    user_id BIGINT,
    client_id VARCHAR(100),
    
    -- Request context
    ip_address VARCHAR(45),
    user_agent TEXT,
    request_uri TEXT,
    request_method VARCHAR(10),
    session_id VARCHAR(255),
    correlation_id VARCHAR(100),
    
    -- Event details
    result VARCHAR(20) NOT NULL,
    result_code VARCHAR(50),
    error_message TEXT,
    
    -- OAuth2 specific fields
    grant_type VARCHAR(50),
    scopes TEXT,
    token_type VARCHAR(50),
    authorization_code_id VARCHAR(255),
    
    -- Additional metadata as JSON (using CLOB for H2)
    details CLOB,
    
    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Performance indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_audit_event_type ON security_audit_events(event_type);
CREATE INDEX IF NOT EXISTS idx_audit_event_category ON security_audit_events(event_category);
CREATE INDEX IF NOT EXISTS idx_audit_event_timestamp ON security_audit_events(event_timestamp);
CREATE INDEX IF NOT EXISTS idx_audit_principal ON security_audit_events(principal);
CREATE INDEX IF NOT EXISTS idx_audit_client_id ON security_audit_events(client_id);
CREATE INDEX IF NOT EXISTS idx_audit_user_id ON security_audit_events(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_result ON security_audit_events(result);
CREATE INDEX IF NOT EXISTS idx_audit_ip_address ON security_audit_events(ip_address);
CREATE INDEX IF NOT EXISTS idx_audit_session_id ON security_audit_events(session_id);
CREATE INDEX IF NOT EXISTS idx_audit_correlation_id ON security_audit_events(correlation_id);

-- Composite index for time-range queries with filtering
CREATE INDEX IF NOT EXISTS idx_audit_timestamp_type ON security_audit_events(event_timestamp, event_type);
CREATE INDEX IF NOT EXISTS idx_audit_timestamp_principal ON security_audit_events(event_timestamp, principal);
